<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminPanel.aspx.cs" Inherits="AgriculTemplate.AdminPanel" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Admin</title>
    <link rel="stylesheet" href="cssAdmin/styleAdmin.css"/>
    <style type="text/css">

        table{
            margin-left:auto;
            margin-right:auto;   
            text-align:center;
            width:800px;            
        }
        .font{
            font-size:30px;
            text-align:center;
        }
        .auto-style2{
            margin-left:50%;
             width: 100%;
        }
        #form1{
           
        }
       
    </style>
</head>
<body>
      <div class="sidebar">
    <div class="logo-details">
      <i class='bx bxl-c-plus-plus'></i>
      <span class="logo_name">Admin Panel</span>
    </div>
      <ul class="nav-links">
        <li>
          <a href="AdminShow.aspx" >
            <i class='bx bx-grid-alt' ></i>
            <span class="links_name">Dashboard</span>
          </a>
        </li>
        <li>
          <a href="AdminPanel.aspx" class="active">
            <i class='bx bx-box' ></i>
            <span class="links_name">Product</span>
          </a>
        </li>
        <li>
          <a href="Order.aspx">
            <i class='bx bx-list-ul' ></i>
            <span class="links_name">Order list</span>
          </a>
        </li>
        <li>
          <a href="UserShow.aspx">
            <i class='bx bx-pie-chart-alt-2' ></i>
            <span class="links_name">User</span>
          </a>
        </li>
       
        <li class="log_out">
          <a href="Login2.aspx">
            <i class='bx bx-log-out'></i>
            <span class="links_name">Log out</span>
          </a>
        </li>
      </ul>
  </div>
    
    
         
    <form id="form1" runat="server">
         
        <div class="auto-style1">
            <table >
                <tr class="font">
                    <td colspan="2">Product</td>
                </tr>
               
                <tr>
                   
                </tr>
               
                <tr class="auto-style2">
                    <td colspan="2">
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="Vertical" ShowFooter="True" >
                            <AlternatingRowStyle BackColor="#CCCCCC" />
                            <Columns>
                                <asp:TemplateField HeaderText="Id" InsertVisible="False" SortExpression="Id">
                                    <EditItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                                    </ItemTemplate>
                                    <FooterTemplate>
                                        <asp:LinkButton OnClick="LinkButton1_Click" ValidationGroup="Insert" ID="LinkButton1" runat="server">Insert</asp:LinkButton>
                                    </FooterTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="name" SortExpression="name">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                                        <asp:RequiredFieldValidator ControlToValidate="TextBox1" ForeColor="Red" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator1" runat="server" ErrorMessage="Name is required"></asp:RequiredFieldValidator>     
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                                    </ItemTemplate>
                                    <FooterTemplate>
                                        <asp:TextBox ID="FooterName" runat="server"></asp:TextBox>
                                        <asp:RequiredFieldValidator ValidationGroup="Insert" ControlToValidate="FooterName" ForeColor="Red" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator2" runat="server" ErrorMessage="Name is required"></asp:RequiredFieldValidator>
                                      </FooterTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="type" SortExpression="type">
                                    <EditItemTemplate>
                                         <asp:DropDownList ID="DropDownList1" runat="server"  Text='<%# Bind("type") %>'>
                                            <asp:ListItem>Select type</asp:ListItem>
                                            <asp:ListItem>Wheat</asp:ListItem>
                                            <asp:ListItem>Rice</asp:ListItem>
                                            <asp:ListItem>Jute</asp:ListItem>
                                            <asp:ListItem>Barley</asp:ListItem>
                                            <asp:ListItem>Potato</asp:ListItem>
                                            <asp:ListItem>Cotton</asp:ListItem>
                                            <asp:ListItem>Corn</asp:ListItem>
                                            <asp:ListItem>Chemical</asp:ListItem>
                                            <asp:ListItem>Organic</asp:ListItem>
                                            <asp:ListItem>Biofertilisers</asp:ListItem>
                                        </asp:DropDownList>
                                         <asp:RequiredFieldValidator InitialValue="Select type" ControlToValidate="DropDownList1" ForeColor="Red" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator3" runat="server" ErrorMessage="Type is required"></asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("type") %>'></asp:Label>
                                    </ItemTemplate>
                                    <FooterTemplate>
                                        <asp:DropDownList ID="FooterDdlType" runat="server">
                                            <asp:ListItem>Select type</asp:ListItem>
                                            <asp:ListItem>Wheat</asp:ListItem>
                                            <asp:ListItem>Rice</asp:ListItem>
                                            <asp:ListItem>Jute</asp:ListItem>
                                            <asp:ListItem>Barley</asp:ListItem>
                                            <asp:ListItem>Potato</asp:ListItem>
                                            <asp:ListItem>Cotton</asp:ListItem>
                                            <asp:ListItem>Corn</asp:ListItem>
                                            <asp:ListItem>Chemical</asp:ListItem>
                                            <asp:ListItem>Organic</asp:ListItem>
                                            <asp:ListItem>Biofertilisers</asp:ListItem>
                                        </asp:DropDownList>
                                         <asp:RequiredFieldValidator ValidationGroup="Insert" InitialValue="Select type" ControlToValidate="FooterDdlType" ForeColor="Red" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator4" runat="server" ErrorMessage="Type is required"></asp:RequiredFieldValidator>
                                    </FooterTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="details" SortExpression="details">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("details") %>'></asp:TextBox>
                                    <asp:RequiredFieldValidator ControlToValidate="TextBox3" ForeColor="Red" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator5" runat="server" ErrorMessage="Details is required"></asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("details") %>'></asp:Label>
                                    </ItemTemplate>
                                    <FooterTemplate>
                                        <asp:TextBox ID="FooterClass" runat="server"></asp:TextBox>
                                     <asp:RequiredFieldValidator ValidationGroup="Insert" ControlToValidate="FooterClass" ForeColor="Red" Text="*" SetFocusOnError="true" ID="RequiredFieldValidator6" runat="server" ErrorMessage="Details is required"></asp:RequiredFieldValidator>
                                    </FooterTemplate>
                                </asp:TemplateField>
                            </Columns>
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#808080" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#383838" />
                        </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:ValidationSummary ValidationGroup="Insert" ID="ValidationSummary1" runat="server" BackColor="#CCCCCC" Font-Size="Larger" ForeColor="Red" /> </td>
                </tr>
                 <tr>
                    <td colspan="2">
                        <asp:ValidationSummary ID="ValidationSummary2" runat="server" BackColor="#CCCCCC" Font-Size="Larger" ForeColor="Red" /> </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Product] WHERE [Id] = @Id" InsertCommand="INSERT INTO [Product] ([name], [type], [details]) VALUES (@name, @type, @details)" SelectCommand="SELECT * FROM [Product]" UpdateCommand="UPDATE [Product] SET [name] = @name, [type] = @type, [details] = @details WHERE [Id] = @Id">
                            <DeleteParameters>
                                <asp:Parameter Name="Id" Type="Int32" />
                            </DeleteParameters>
                            <InsertParameters>
                                <asp:Parameter Name="name" Type="String" />
                                <asp:Parameter Name="type" Type="String" />
                                <asp:Parameter Name="details" Type="String" />
                            </InsertParameters>
                            <UpdateParameters>
                                <asp:Parameter Name="name" Type="String" />
                                <asp:Parameter Name="type" Type="String" />
                                <asp:Parameter Name="details" Type="String" />
                                <asp:Parameter Name="Id" Type="Int32" />
                            </UpdateParameters>
                        </asp:SqlDataSource>
                    </td>
                </tr>
            </table>
        </div>
    </form>
        
</body>
</html>
